apiVersion: v1
kind: Pod
metadata:
  name: redis-app
  labels:
    name: redis-app
    app: demo-voting-app
spec:
  containers:
  - name: redis-app
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
    ports:
      - containerPort: 6379