apiVersion: v1
kind: Pod
metadata:
  name: result-app
  labels:
    name: result-app
    app: demo-voting-app
spec:
  containers:
  - name: result-app
    image: dockersamples/examplevotingapp_result
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
    ports:
      - containerPort: 80 