apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: demo-voting-app
spec:
  type: LoadBalancer
  selector:
    name: result-app
    app: demo-voting-app
  ports:
  - port: 80
    targetPort: 80
